# Generated by Django 4.2.16 on 2024-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LettersGameAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='date_used',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
